### ISSUE TITLE
"easyfile" should be "easy-file"

### ISSUE THREAD

**Issue by klkblake** [dmbarbour/wikilon#1]
Dependency resolution fails as the package "easyfile" does not exist -- it should be "easy-file". Additionally, hsrc_lib/Wikilon/Time.hs wants the time and old-locale packages. (I get the impression HEAD isn't meant to successfully build at the moment, but I thought I'd report these as they might not show up on your system.)

**Comment by dmbarbour** [comment]
Thanks. I'm still mostly reviewing old design docs at the moment, and don't
expect this to build right now.
